version: '3.8'

services:
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - ./.env
    ports:
      - 443:443
      - 80:80
      - 9229:9229
    volumes:
      - ./src:/workspace/src
    restart: on-failure
